USE DATABASE HEALTHCARE_AI_DB;
 USE SCHEMA DRUG_ANALYTICS; 
USE WAREHOUSE CORTEX_WH; 
-- Step 1: Create Internal Stage 
CREATE OR REPLACE STAGE DRUG_REVIEWS_STAGE 
FILE_FORMAT = ( 
TYPE = 'CSV' 
FIELD_DELIMITER = ',' 
SKIP_HEADER = 1 
FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
NULL_IF = ('NULL', 'null', '') 
EMPTY_FIELD_AS_NULL = TRUE );
 
-- Step 2: Upload files via SnowSQL CLI
 -- PUT file://drugsComTrain_raw.csv @DRUG_REVIEWS_STAGE;
 -- PUT file://drugsComTest_raw.csv @DRUG_REVIEWS_STAGE; 
-- Step 3: Load staged files into table 
COPY INTO RAW_DRUG_REVIEWS 
FROM @DRUG_REVIEWS_STAGE 
PATTERN = '.*drugsComTrain.*|.*drugsComTest.*' 
ON_ERROR = 'CONTINUE'; 
-- Step 4: Verify load
 SELECT COUNT(*) AS TOTAL_RECORDS FROM RAW_DRUG_REVIEWS; 
SELECT * FROM RAW_DRUG_REVIEWS LIMIT 5;
