CREATE DATABASE IF NOT EXISTS HEALTHCARE_AI_DB; 
USE DATABASE HEALTHCARE_AI_DB; 
CREATE SCHEMA IF NOT EXISTS DRUG_ANALYTICS;
 USE SCHEMA DRUG_ANALYTICS;
 CREATE WAREHOUSE IF NOT EXISTS CORTEX_WH 
WAREHOUSE_SIZE = 'X-SMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE 
COMMENT = 'Warehouse for Cortex LLM project'; 
USE WAREHOUSE CORTEX_WH;
 
CREATE OR REPLACE TABLE RAW_DRUG_REVIEWS ( 
UNIQUE_ID INTEGER, 
DRUG_NAME VARCHAR(200),
 CONDITION VARCHAR(500), 
REVIEW TEXT, 
RATING FLOAT, 
REVIEW_DATE VARCHAR(50), 
USEFUL_COUNT INTEGER 
);
